 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClasesInternas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Vivia Jones
 */
public class CreateCashier extends javax.swing.JInternalFrame {

    static ResultSet res;
    int cont;
    /**
     * Creates new form CreateCashier
     */
    public CreateCashier() {
        initComponents();
        setLocation(200, 50);
        CargarArticulo();
    }
    
    public void CargarArticulo(){
        DefaultTableModel modelo = (DefaultTableModel) CajeroTablatbl.getModel();
        modelo.setRowCount(0);
        try{
            PreparedStatement stmt = ClasesInternas.ConexionAdmin.getConexion().
                prepareStatement("SELECT idvendedor, nombre, apellido,"
                        + "cedula, email FROM Vendedor");
            res = stmt.executeQuery();
            while(res.next()){
             Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));
                modelo.addRow(v);
                CajeroTablatbl.setModel(modelo);
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulolbl = new javax.swing.JLabel();
        CajeroIdlbl = new javax.swing.JLabel();
        CajeroIdtxt = new javax.swing.JTextField();
        CajeroNombrelbl = new javax.swing.JLabel();
        CajeroNombretxt = new javax.swing.JTextField();
        CajeroApellidolbl = new javax.swing.JLabel();
        CajeroApellidotxt = new javax.swing.JTextField();
        CajeroCedulalbl = new javax.swing.JLabel();
        Emaillbl = new javax.swing.JLabel();
        Contrasenalbl = new javax.swing.JLabel();
        CajeroCedulatxt = new javax.swing.JTextField();
        CajeroEmailtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CajeroTablatbl = new javax.swing.JTable();
        CrearCajerobtn = new javax.swing.JButton();
        EliminarCajerobtn = new javax.swing.JButton();
        CajeroActualizarbtn = new javax.swing.JButton();
        CajeroContrasenatxt = new javax.swing.JPasswordField();

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Titulolbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulolbl.setText("Nuevo Cajero");

        CajeroIdlbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CajeroIdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CajeroIdlbl.setText("Cajero Id");

        CajeroIdtxt.setMinimumSize(new java.awt.Dimension(6, 26));

        CajeroNombrelbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CajeroNombrelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CajeroNombrelbl.setText("Nombre");

        CajeroApellidolbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CajeroApellidolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CajeroApellidolbl.setText("Apellido");

        CajeroCedulalbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CajeroCedulalbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CajeroCedulalbl.setText("Cedula");

        Emaillbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Emaillbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emaillbl.setText("E-Mail");

        Contrasenalbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Contrasenalbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contrasenalbl.setText("Contraseña");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        CajeroTablatbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cedula", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CajeroTablatbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajeroTablatblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CajeroTablatbl);

        CrearCajerobtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CrearCajerobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/an.png"))); // NOI18N
        CrearCajerobtn.setText("Agregar");
        CrearCajerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCajerobtnActionPerformed(evt);
            }
        });

        EliminarCajerobtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        EliminarCajerobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/del.png"))); // NOI18N
        EliminarCajerobtn.setText("Eliminar");
        EliminarCajerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCajerobtnActionPerformed(evt);
            }
        });

        CajeroActualizarbtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CajeroActualizarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        CajeroActualizarbtn.setText("Actualizar");
        CajeroActualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajeroActualizarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Titulolbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajeroApellidolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CajeroNombrelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CajeroIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CajeroCedulalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Emaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Contrasenalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajeroIdtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CajeroNombretxt)
                            .addComponent(CajeroApellidotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(CajeroCedulatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(CajeroEmailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(CajeroContrasenatxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CrearCajerobtn)
                        .addGap(18, 18, 18)
                        .addComponent(CajeroActualizarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(EliminarCajerobtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulolbl)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CajeroIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CajeroIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CajeroNombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(CajeroNombrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(CajeroApellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(CajeroApellidolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CajeroCedulalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CajeroCedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CajeroEmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Contrasenalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CajeroContrasenatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(69, 69, 69)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CrearCajerobtn)
                                .addComponent(EliminarCajerobtn)
                                .addComponent(CajeroActualizarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearCajerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCajerobtnActionPerformed
        // TODO add your handling code here:
        if(CajeroNombretxt.getText().isEmpty() ||
                CajeroApellidotxt.getText().isEmpty() || 
                CajeroCedulatxt.getText().isEmpty() ||
                CajeroEmailtxt.getText().isEmpty() ||
                CajeroContrasenatxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los espacios",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            CajeroNombretxt.setText("");
            CajeroApellidotxt.setText("");
            CajeroCedulatxt.setText("");
            CajeroEmailtxt.setText("");
            CajeroContrasenatxt.setText("");
            CajeroNombretxt.requestFocus();
            CajeroApellidotxt.requestFocus();
            CajeroCedulatxt.requestFocus();
            CajeroEmailtxt.requestFocus();
            CajeroContrasenatxt.requestFocus();
            
        }else{
            try{
                PreparedStatement stmt = ClasesInternas.ConexionCashier.
                        getConexion().prepareStatement("SELECT COUNT (cedula)"
                                + " FROM Vendedor WHERE cedula = ?");
                stmt.setString(1, CajeroCedulatxt.getText());
                res = stmt.executeQuery();
                try{
                    while(res.next()){
                        cont = res.getInt(1);
                    }
                stmt.close();
                res.close();
                }catch(SQLException e){
                    e.getMessage();
                }
            if(cont >= 1){
                JOptionPane.showMessageDialog(this, "La cedula ya existe!",
                        "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                CajeroNombretxt.setText("");
                CajeroApellidotxt.setText("");
                CajeroCedulatxt.setText("");
                CajeroEmailtxt.setText("");
                CajeroContrasenatxt.setText("");
                CajeroNombretxt.requestFocus();
                CajeroApellidotxt.requestFocus();
                CajeroCedulatxt.requestFocus();
                CajeroEmailtxt.requestFocus();
                CajeroContrasenatxt.requestFocus();
            }else{
                
               try{
                   stmt = ClasesInternas.ConexionCashier.
                        getConexion().prepareStatement("INSERT INTO Vendedor VALUES (?, ?, ?, ?, ?)");
                stmt.setString(1, CajeroNombretxt.getText());
                stmt.setString(2, CajeroApellidotxt.getText());
                stmt.setString(3, CajeroCedulatxt.getText());
                stmt.setString(4, CajeroEmailtxt.getText());
                stmt.setString(5, CajeroContrasenatxt.getText());
                res = stmt.executeQuery();
                stmt.close();
                res.close();
               }catch(SQLException e){
                   e.getMessage();
               }
               JOptionPane.showMessageDialog(this, "LOS DATOS HAN SIDO GUARDADOS CORRECTAMENTE",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
               CargarArticulo();

                /*stmt = ClasesInternas.ConexionCashier.
                        getConexion().prepareStatement("SELECT * FROM "
                                + "Vendedor WHERE cedula = ?");
                res = stmt.executeQuery();
                if (res.next()) {
                    CajeroIdtxt.setText(res.getString(1));
                }*/

            }
        }catch(SQLException e){
            e.getMessage();
        }
    }
    }//GEN-LAST:event_CrearCajerobtnActionPerformed

    private void CajeroActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajeroActualizarbtnActionPerformed
        // TODO add your handling code here:
        int opc =JOptionPane.showConfirmDialog(this, "¿ESTA SEGURO QUE "
                + "DESEA MODIFICAR ESTE CAJERO?", "INFO", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(opc == JOptionPane.YES_OPTION){
        try{
            PreparedStatement stmt = ClasesInternas.ConexionCashier.
                    getConexion().prepareStatement("UPDATE Vendedor SET "
                            + "nombre = ?, apellido = ?, cedula = ?,"
                            + "email = ?, pass = ? WHERE idvendedor = ?");
            stmt.setString(1, CajeroNombretxt.getText());
            stmt.setString(2, CajeroApellidotxt.getText());
            stmt.setString(3, CajeroCedulatxt.getText());
            stmt.setString(4, CajeroEmailtxt.getText());
            stmt.setString(5, CajeroContrasenatxt.getText());
            stmt.setInt(6, Integer.parseInt(CajeroIdtxt.getText()));
            res = stmt.executeQuery();
                JOptionPane.showMessageDialog(this, "Datos Actualizados!", 
                        "INFO", JOptionPane.INFORMATION_MESSAGE);
            stmt.close();
            res.close();
        }catch(SQLException e){
            e.getMessage();
        }
        CargarArticulo();
      }
    }//GEN-LAST:event_CajeroActualizarbtnActionPerformed

    private void EliminarCajerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCajerobtnActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE"
                + " DESEA ELIMINAR ESTE CAJERO?", "INFO", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(opc == JOptionPane.YES_OPTION){
        try{
            PreparedStatement stmt = ClasesInternas.ConexionCashier.
                getConexion().prepareStatement("DELETE FROM Vendedor "
                        + "WHERE idvendedor = ?");
            stmt.setInt(1, Integer.parseInt(CajeroIdtxt.getText()));
            res = stmt.executeQuery();
            JOptionPane.showMessageDialog(this, "Borrado exitoso!",
                        "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            stmt.close();
            res.close();
        }catch(SQLException e){
            e.getMessage();
        }
       CargarArticulo();
      }
    }//GEN-LAST:event_EliminarCajerobtnActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void CajeroTablatblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajeroTablatblMouseClicked
        // TODO add your handling code here:
        int selectedRow = CajeroTablatbl.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)CajeroTablatbl.getModel();
        CajeroIdtxt.setText(modelo.getValueAt(selectedRow, 0).toString());
        CajeroNombretxt.setText(modelo.getValueAt(selectedRow, 1).toString());
        CajeroApellidotxt.setText(modelo.getValueAt(selectedRow, 2).toString());
        CajeroCedulatxt.setText(modelo.getValueAt(selectedRow, 3).toString());
        CajeroEmailtxt.setText(modelo.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_CajeroTablatblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CajeroActualizarbtn;
    private javax.swing.JLabel CajeroApellidolbl;
    private javax.swing.JTextField CajeroApellidotxt;
    private javax.swing.JLabel CajeroCedulalbl;
    private javax.swing.JTextField CajeroCedulatxt;
    private javax.swing.JPasswordField CajeroContrasenatxt;
    private javax.swing.JTextField CajeroEmailtxt;
    private javax.swing.JLabel CajeroIdlbl;
    private javax.swing.JTextField CajeroIdtxt;
    private javax.swing.JLabel CajeroNombrelbl;
    private javax.swing.JTextField CajeroNombretxt;
    private javax.swing.JTable CajeroTablatbl;
    private javax.swing.JLabel Contrasenalbl;
    private javax.swing.JButton CrearCajerobtn;
    private javax.swing.JButton EliminarCajerobtn;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JLabel Titulolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
