/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClasesInternas;

import static ClasesInternas.CreateCashier.res;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vivia Jones
 */
public class UpdateProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateProducts
     */
    public UpdateProducts() {
        initComponents();
        setTitle("Administración de Productos");
        setLocation(200, 50);
        ComboRefrescar();
        CargarArticulo();
    }
    public void CargarArticulo(){
        DefaultTableModel modelo = (DefaultTableModel) ProductoTablatbl.getModel();
        modelo.setRowCount(0);
        try{
            PreparedStatement stmt = ClasesInternas.ConexionAdmin.getConexion().
                prepareStatement("SELECT Producto.idproducto, Producto.nombre,"
                        + " Producto.precio, Producto.stock, Categoria.nombre "
                        + "FROM Producto\n" + "INNER JOIN Categoria ON "
                        + "Producto.idcategoria = Categoria.idcategoria;");
            res = stmt.executeQuery();
            while(res.next()){
             Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getFloat(3));
                v.add(res.getInt(4));
                v.add(res.getString(5));
                modelo.addRow(v);
                ProductoTablatbl.setModel(modelo);
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }
    
    public void ComboRefrescar(){
        try{
            PreparedStatement stmt = ClasesInternas.ConexionAdmin.getConexion()
                    .prepareStatement("SELECT idcategoria, nombre, descripcion"
                            + " FROM Categoria");
            ResultSet res = stmt.executeQuery();
            int idcat = 0;
            String mNombre = "";
            String mDescripcion = "";
            Productos pro = new Productos(idcat, mNombre, mDescripcion);
            //ProductoCategoriacmbx.removeAllItems();
            while(res.next()){
                ProductoCategoriacmbx.addItem(res.getString(2));
                idcat = res.getInt(1);
                mNombre = res.getString(2);
                mDescripcion = res.getString(3);
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulolbl = new javax.swing.JLabel();
        ProductoIdlbl = new javax.swing.JLabel();
        ProductoNombrelbl = new javax.swing.JLabel();
        ProductoPreciolbl = new javax.swing.JLabel();
        ProductoStocklbl = new javax.swing.JLabel();
        ProductoCategorialbl = new javax.swing.JLabel();
        ProductoIdtxt = new javax.swing.JTextField();
        ProductoNombretxt = new javax.swing.JTextField();
        ProductoPreciotxt = new javax.swing.JTextField();
        ProductoStocktxt = new javax.swing.JTextField();
        ProductoCategoriacmbx = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductoTablatbl = new javax.swing.JTable();
        ProductoNuevobtn = new javax.swing.JButton();
        ProductoActualizarbtn = new javax.swing.JButton();
        Eliminarbtn = new javax.swing.JButton();

        setClosable(true);

        Titulolbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulolbl.setText("Administración de Productos");

        ProductoIdlbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoIdlbl.setText("Producto Id");

        ProductoNombrelbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoNombrelbl.setText("Nombre Producto");

        ProductoPreciolbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoPreciolbl.setText("Precio Producto");

        ProductoStocklbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoStocklbl.setText("Stock Producto");

        ProductoCategorialbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoCategorialbl.setText("Categoria Producto");

        ProductoCategoriacmbx.setToolTipText("");
        ProductoCategoriacmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoCategoriacmbxActionPerformed(evt);
            }
        });

        ProductoTablatbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ProductoId", "Nombre", "Precio", "Stock", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductoTablatbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoTablatblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductoTablatbl);

        ProductoNuevobtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoNuevobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/07_plus-20.png"))); // NOI18N
        ProductoNuevobtn.setText("Nuevo");
        ProductoNuevobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoNuevobtnActionPerformed(evt);
            }
        });

        ProductoActualizarbtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ProductoActualizarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        ProductoActualizarbtn.setText("Actualizar");
        ProductoActualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActualizarbtnActionPerformed(evt);
            }
        });

        Eliminarbtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Eliminarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/del.png"))); // NOI18N
        Eliminarbtn.setText("Eliminar");
        Eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoIdlbl)
                            .addComponent(ProductoNombrelbl)
                            .addComponent(ProductoPreciolbl)
                            .addComponent(ProductoStocklbl)
                            .addComponent(ProductoCategorialbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(ProductoNuevobtn)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProductoIdtxt)
                                    .addComponent(ProductoNombretxt)
                                    .addComponent(ProductoPreciotxt)
                                    .addComponent(ProductoStocktxt)
                                    .addComponent(ProductoCategoriacmbx, 0, 168, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(ProductoActualizarbtn)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulolbl)
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(Eliminarbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulolbl)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProductoNombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoNombrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoPreciolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoPreciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoStocklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoStocktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoCategorialbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoCategoriacmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoNuevobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoActualizarbtn))
                        .addGap(18, 18, 18)
                        .addComponent(Eliminarbtn)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductoNuevobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoNuevobtnActionPerformed
        // TODO add your handling code here:
        if(ProductoNombretxt.getText().isEmpty() ||
                ProductoPreciotxt.getText().isEmpty() || 
                ProductoStocktxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los espacios",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            ProductoNombretxt.setText("");
            ProductoPreciotxt.setText("");
            ProductoStocktxt.setText("");
            ProductoNombretxt.requestFocus();
            ProductoPreciotxt.requestFocus();
            ProductoStocktxt.requestFocus();
        }else{
            try{
                PreparedStatement stmt = ClasesInternas.ConexionAdmin.
                        getConexion().prepareStatement("INSERT INTO Producto"
                                + " (idcategoria, nombre, precio, stock) VALUES "
                                + "(?, ?, ?, ?)");
                stmt.setInt(1, ProductoCategoriacmbx.getSelectedIndex() + 1);
                stmt.setString(2, ProductoNombretxt.getText());
                stmt.setString(3, ProductoPreciotxt.getText());
                stmt.setString(4, ProductoStocktxt.getText());
                ResultSet res = stmt.executeQuery();
                stmt.close();
                res.close();
            }catch(SQLException e){
                e.getMessage();
            }
        }
        CargarArticulo();
    }//GEN-LAST:event_ProductoNuevobtnActionPerformed

    private void ProductoCategoriacmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoCategoriacmbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoCategoriacmbxActionPerformed

    private void ProductoActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActualizarbtnActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "¿ESTA SEGURO QUE DESEA "
                + "MODIFICAR EL PRODUCTO?", "INFO", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(opc == JOptionPane.YES_OPTION){
            try{
                
                PreparedStatement stmt = ClasesInternas.ConexionAdmin.
                        getConexion().prepareStatement("UPDATE Producto SET "
                                + "idcategoria = ?, nombre = ?, precio = ?, "
                                + "stock = ? WHERE idproducto = ?");
                stmt.setInt(1, ProductoCategoriacmbx.getSelectedIndex() + 1);
                stmt.setString(2, ProductoNombretxt.getText());
                stmt.setString(3, ProductoPreciotxt.getText());
                stmt.setString(4, ProductoStocktxt.getText());
                stmt.setString(5, ProductoIdtxt.getText());
                ResultSet res = stmt.executeQuery();
                JOptionPane.showMessageDialog(this, "Datos Actualizados!", 
                        "INFO", JOptionPane.INFORMATION_MESSAGE);
                stmt.close();
                res.close();
            }catch(SQLException e){
                e.getMessage();
            }
        }
        CargarArticulo();
    }//GEN-LAST:event_ProductoActualizarbtnActionPerformed

    private void ProductoTablatblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductoTablatblMouseClicked
        // TODO add your handling code here:
        int selectedRow = ProductoTablatbl.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)ProductoTablatbl.getModel();
        ProductoIdtxt.setText(modelo.getValueAt(selectedRow, 0).toString());
        ProductoNombretxt.setText(modelo.getValueAt(selectedRow, 1).toString());
        ProductoPreciotxt.setText(modelo.getValueAt(selectedRow, 2).toString());
        ProductoStocktxt.setText(modelo.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_ProductoTablatblMouseClicked

    private void EliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtnActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "¿ESTA SEGURO QUE DESEA "
                + "ELIMINAR EL PRODUCTO?", "INFO", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(opc == JOptionPane.YES_OPTION){
            
            try{
                
                PreparedStatement stmt = ClasesInternas.ConexionAdmin
                        .getConexion()
                        .prepareStatement("DELETE FROM Producto WHERE idproducto = ?");
                
                stmt.setInt(1, Integer.parseInt(ProductoIdtxt.getText()));
                
                stmt.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Producto Eliminado!", "INFO", JOptionPane.INFORMATION_MESSAGE);
                
                CargarArticulo();
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
            
        }else{
            
        }
    }//GEN-LAST:event_EliminarbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminarbtn;
    private javax.swing.JButton ProductoActualizarbtn;
    private javax.swing.JComboBox<String> ProductoCategoriacmbx;
    private javax.swing.JLabel ProductoCategorialbl;
    private javax.swing.JLabel ProductoIdlbl;
    private javax.swing.JTextField ProductoIdtxt;
    private javax.swing.JLabel ProductoNombrelbl;
    private javax.swing.JTextField ProductoNombretxt;
    private javax.swing.JButton ProductoNuevobtn;
    private javax.swing.JLabel ProductoPreciolbl;
    private javax.swing.JTextField ProductoPreciotxt;
    private javax.swing.JLabel ProductoStocklbl;
    private javax.swing.JTextField ProductoStocktxt;
    private javax.swing.JTable ProductoTablatbl;
    private javax.swing.JLabel Titulolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
