package Main;

import ClasesInternas.CreateCashier;
import ClasesInternas.MostrarFactura;
import ClasesInternas.UpdateProducts;
import java.awt.Toolkit;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SAMEER
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public AdminMenu() {
        initComponents();
        setTitle("Menu de Administrador");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Cajerobtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        Stockbtn = new javax.swing.JButton();
        Facturasbtn = new javax.swing.JButton();
        CerrarSesionbtn = new javax.swing.JButton();
        Logolbl = new javax.swing.JLabel();
        ColoFondo = new javax.swing.JLabel();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quick Bill");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setUndecorated(true);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cajerobtn.setBackground(new java.awt.Color(255, 197, 101));
        Cajerobtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cajerobtn.setForeground(new java.awt.Color(0, 0, 14));
        Cajerobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/an.png"))); // NOI18N
        Cajerobtn.setText("Cajero");
        Cajerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajerobtnActionPerformed(evt);
            }
        });
        jPanel1.add(Cajerobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 110, 40));

        Salirbtn.setBackground(new java.awt.Color(255, 197, 101));
        Salirbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salirbtn.setForeground(new java.awt.Color(0, 0, 14));
        Salirbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        Salirbtn.setText("Salir");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Salirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, 40));

        Stockbtn.setBackground(new java.awt.Color(255, 197, 101));
        Stockbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Stockbtn.setForeground(new java.awt.Color(0, 0, 14));
        Stockbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock.png"))); // NOI18N
        Stockbtn.setText("Stock");
        Stockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Stockbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 40));

        Facturasbtn.setBackground(new java.awt.Color(255, 197, 101));
        Facturasbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Facturasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/receipt.png"))); // NOI18N
        Facturasbtn.setText("Facturas");
        Facturasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Facturasbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 120, 40));

        CerrarSesionbtn.setBackground(new java.awt.Color(255, 197, 101));
        CerrarSesionbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CerrarSesionbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_1.png"))); // NOI18N
        CerrarSesionbtn.setText("Cerrar Sesión");
        CerrarSesionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionbtnActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarSesionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, 40));

        Logolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSFW.PNG"))); // NOI18N
        jPanel1.add(Logolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ColoFondo.setBackground(new java.awt.Color(255, 197, 101));
        ColoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bk.jpg"))); // NOI18N
        jPanel1.add(ColoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_SalirbtnActionPerformed

    private void CajerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajerobtnActionPerformed
        // TODO add your handling code here:
        CreateCashier cash = new CreateCashier();
        this.desktop.add(cash);
        cash.setVisible(true);
    }//GEN-LAST:event_CajerobtnActionPerformed

    private void StockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockbtnActionPerformed
        // TODO add your handling code here:
        UpdateProducts producto = new UpdateProducts();
        this.desktop.add(producto);
        producto.setVisible(true);
    }//GEN-LAST:event_StockbtnActionPerformed

    private void CerrarSesionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionbtnActionPerformed
        // TODO add your handling code here:
        AdminLogin log = new AdminLogin();
        dispose();
        log.setVisible(true);
        
    }//GEN-LAST:event_CerrarSesionbtnActionPerformed

    private void FacturasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasbtnActionPerformed
        // TODO add your handling code here:
        MostrarFactura factura = new MostrarFactura();
        this.desktop.add(factura);
        factura.setVisible(true);
    }//GEN-LAST:event_FacturasbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminMenu().setVisible(true);
        
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cajerobtn;
    private javax.swing.JButton CerrarSesionbtn;
    private javax.swing.JLabel ColoFondo;
    private javax.swing.JButton Facturasbtn;
    private javax.swing.JLabel Logolbl;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JButton Stockbtn;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
