/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import ClasesInternas.AutenticacionAdmin;
import javax.swing.JOptionPane;

/**
 *
 * @author Vivia Jones
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        setLocationRelativeTo(null);
        Regresarbtn.setOpaque(false);
        Regresarbtn.setContentAreaFilled(false);
        Regresarbtn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titutlolbl = new javax.swing.JLabel();
        AdminIdlbl = new javax.swing.JLabel();
        PasswordAdminlbl = new javax.swing.JLabel();
        IDimg = new javax.swing.JLabel();
        Passimg = new javax.swing.JLabel();
        AdminIdTXT = new javax.swing.JTextField();
        AdminLoginBTN = new javax.swing.JButton();
        AdminPassJPF = new javax.swing.JPasswordField();
        Regresarbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        Titutlolbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titutlolbl.setForeground(new java.awt.Color(57, 113, 177));
        Titutlolbl.setText("Login Administrador");

        AdminIdlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdminIdlbl.setForeground(new java.awt.Color(57, 113, 177));
        AdminIdlbl.setText("Correo:");

        PasswordAdminlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordAdminlbl.setForeground(new java.awt.Color(57, 113, 177));
        PasswordAdminlbl.setText("Password:");

        IDimg.setForeground(new java.awt.Color(57, 113, 177));
        IDimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/an.png"))); // NOI18N

        Passimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clave.png"))); // NOI18N

        AdminIdTXT.setBackground(new java.awt.Color(32, 33, 35));
        AdminIdTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminIdTXT.setForeground(new java.awt.Color(255, 255, 255));
        AdminIdTXT.setBorder(null);

        AdminLoginBTN.setBackground(new java.awt.Color(126, 87, 194));
        AdminLoginBTN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        AdminLoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        AdminLoginBTN.setText("LOGIN");
        AdminLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginBTNActionPerformed(evt);
            }
        });

        AdminPassJPF.setBackground(new java.awt.Color(32, 33, 35));
        AdminPassJPF.setForeground(new java.awt.Color(255, 255, 255));
        AdminPassJPF.setBorder(null);
        AdminPassJPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPassJPFActionPerformed(evt);
            }
        });

        Regresarbtn.setBackground(new java.awt.Color(32, 33, 35));
        Regresarbtn.setForeground(new java.awt.Color(32, 33, 35));
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow_1.png"))); // NOI18N
        Regresarbtn.setBorder(null);
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Regresarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Titutlolbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDimg)
                            .addComponent(Passimg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(PasswordAdminlbl)
                            .addComponent(AdminIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1)
                            .addComponent(AdminIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminPassJPF)
                            .addComponent(AdminLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Regresarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titutlolbl))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminIdlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDimg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(AdminIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordAdminlbl)
                    .addComponent(Passimg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminPassJPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(AdminLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminPassJPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPassJPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPassJPFActionPerformed

    private void AdminLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBTNActionPerformed
        // TODO add your handling code here:
        String mUser = AdminIdTXT.getText();
        String mPassword = AdminPassJPF.getText();
        
        AutenticacionAdmin autenticacion = new AutenticacionAdmin();
        ClasesInternas.ConexionAdmin.getConexion();
        if(autenticacion.Autenticacion(mUser, mPassword) == true){
            AdminMenu adminmenu = new AdminMenu();
            adminmenu.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido " + mUser + "!",
                    "Felicidades", JOptionPane.INFORMATION_MESSAGE);
            AdminIdTXT.setText("");
            AdminPassJPF.setText("");
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "USUARIO Y CONTRASEÑA INCORRECTO",
                    "Error de Autenticacion", JOptionPane.ERROR_MESSAGE);
            AdminIdTXT.setText("");
            AdminPassJPF.setText("");
        }
    }//GEN-LAST:event_AdminLoginBTNActionPerformed

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        // TODO add your handling code here:
        VPrincipal principal = new VPrincipal();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_RegresarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminIdTXT;
    private javax.swing.JLabel AdminIdlbl;
    private javax.swing.JButton AdminLoginBTN;
    private javax.swing.JPasswordField AdminPassJPF;
    private javax.swing.JLabel IDimg;
    private javax.swing.JLabel Passimg;
    private javax.swing.JLabel PasswordAdminlbl;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JLabel Titutlolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
