/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import ClasesInternas.AutenticacionCashier;
import ClasesInternas.NuevaFactura;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Vivia Jones
 */

public class CashierLogin extends javax.swing.JFrame {

    /**
     * Creates new form CashierLogin
     */
    
    public CashierLogin() {
        initComponents();
        setTitle("Inicio de Sesión");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icon.png")));
        setLocationRelativeTo(null);
        Regresarbtn.setOpaque(false);
        Regresarbtn.setContentAreaFilled(false);
        Regresarbtn.setBorderPainted(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLBL = new javax.swing.JLabel();
        CashierIdLBL = new javax.swing.JLabel();
        CashierPassLBL = new javax.swing.JLabel();
        CashierIMG = new javax.swing.JLabel();
        PassIMG = new javax.swing.JLabel();
        CashierIdTXT = new javax.swing.JTextField();
        CashierLoginBTN = new javax.swing.JButton();
        CashierPassJPF = new javax.swing.JPasswordField();
        Regresarbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        TituloLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloLBL.setForeground(new java.awt.Color(57, 113, 177));
        TituloLBL.setText("Login Cajero");

        CashierIdLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierIdLBL.setForeground(new java.awt.Color(57, 113, 177));
        CashierIdLBL.setText("Correo:");

        CashierPassLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierPassLBL.setForeground(new java.awt.Color(57, 113, 177));
        CashierPassLBL.setText("Password:");

        CashierIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/an.png"))); // NOI18N

        PassIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clave.png"))); // NOI18N

        CashierIdTXT.setBackground(new java.awt.Color(32, 33, 35));
        CashierIdTXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CashierIdTXT.setForeground(new java.awt.Color(255, 255, 255));
        CashierIdTXT.setBorder(null);

        CashierLoginBTN.setBackground(new java.awt.Color(126, 87, 194));
        CashierLoginBTN.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CashierLoginBTN.setText("LOGIN");
        CashierLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierLoginBTNActionPerformed(evt);
            }
        });

        CashierPassJPF.setBackground(new java.awt.Color(32, 33, 35));
        CashierPassJPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CashierPassJPF.setForeground(new java.awt.Color(255, 255, 255));
        CashierPassJPF.setBorder(null);

        Regresarbtn.setBackground(new java.awt.Color(32, 33, 35));
        Regresarbtn.setForeground(new java.awt.Color(32, 33, 35));
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow_1.png"))); // NOI18N
        Regresarbtn.setBorder(null);
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Regresarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(TituloLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CashierIMG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CashierIdLBL)
                                    .addComponent(CashierIdTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PassIMG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CashierPassLBL))
                            .addComponent(CashierPassJPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CashierLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloLBL)
                    .addComponent(Regresarbtn))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CashierIMG)
                    .addComponent(CashierIdLBL))
                .addGap(11, 11, 11)
                .addComponent(CashierIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CashierPassLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassIMG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CashierPassJPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(CashierLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashierLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierLoginBTNActionPerformed
        // TODO add your handling code here:
        //Variables que reciben los datos de los campos de texto
        String mUser = CashierIdTXT.getText();
        String mPassword = CashierPassJPF.getText();
        
        /*
        Este fragmento de codigo se encarga de conectarse y autenticar si el
        usuario y contraseña existen en la base de datos y que los datos sean
        los correctos para poder entrar al menu de cajero
        */
        AutenticacionCashier aut = new AutenticacionCashier();
        //Llama a la clase ConexionCashier para brindar una facil y rapida conexion
        ClasesInternas.ConexionCashier.getConexion();
        //Se valida si los datos son autenticos utilizando la clase
        //AutenticacionCashier
        if(aut.Autenticacion(mUser, mPassword) == true){
            CashierMenu cashiermenu = new CashierMenu();
            cashiermenu.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido " + mUser + "!",
                    "Felicidades", JOptionPane.INFORMATION_MESSAGE);
            CashierIdTXT.setText("");
            CashierPassJPF.setText("");
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "USUARIO Y CONTRASEÑA INCORRECTO",
                    "Error de Autenticacion", JOptionPane.ERROR_MESSAGE);
            CashierIdTXT.setText("");
            CashierPassJPF.setText("");
        }
        
    }//GEN-LAST:event_CashierLoginBTNActionPerformed

    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        // TODO add your handling code here:
        VPrincipal principal = new VPrincipal();
        dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_RegresarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CashierIMG;
    private javax.swing.JLabel CashierIdLBL;
    private javax.swing.JTextField CashierIdTXT;
    private javax.swing.JButton CashierLoginBTN;
    private javax.swing.JPasswordField CashierPassJPF;
    private javax.swing.JLabel CashierPassLBL;
    private javax.swing.JLabel PassIMG;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JLabel TituloLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
