/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import ClasesInternas.AutenticacionCashier;
import ClasesInternas.ConexionCashier;
import static ClasesInternas.ConexionCashier.getConexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vivia Jones
 */

public class CashierLogin extends javax.swing.JFrame {

    /**
     * Creates new form CashierLogin
     */
    
    public CashierLogin() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLBL = new javax.swing.JLabel();
        CashierIdLBL = new javax.swing.JLabel();
        CashierPassLBL = new javax.swing.JLabel();
        CashierIMG = new javax.swing.JLabel();
        PassIMG = new javax.swing.JLabel();
        CashierIdTXT = new javax.swing.JTextField();
        CashierLoginBTN = new javax.swing.JButton();
        CashierPassJPF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        TituloLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloLBL.setText("Inicio de Sesion Cashier");

        CashierIdLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierIdLBL.setText("CashierID:");

        CashierPassLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierPassLBL.setText("Password:");

        CashierIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/an.png"))); // NOI18N

        PassIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clave.png"))); // NOI18N

        CashierLoginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login (1).png"))); // NOI18N
        CashierLoginBTN.setText("LOGIN");
        CashierLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierLoginBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TituloLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CashierIMG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CashierIdLBL))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(PassIMG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CashierPassLBL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CashierIdTXT)
                            .addComponent(CashierPassJPF, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CashierLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLBL)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CashierIMG)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CashierIdLBL)
                        .addComponent(CashierIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CashierPassLBL)
                    .addComponent(PassIMG)
                    .addComponent(CashierPassJPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(CashierLoginBTN)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashierLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierLoginBTNActionPerformed
        // TODO add your handling code here:
        //Variables que reciben los datos de los campos de texto
        String mUser = CashierIdTXT.getText();
        String mPassword = CashierPassJPF.getText();
        
        /*
        Este fragmento de codigo se encarga de conectarse y autenticar si el
        usuario y contraseña existen en la base de datos y que los datos sean
        los correctos para poder entrar al menu de cajero
        */
        AutenticacionCashier aut = new AutenticacionCashier();
        //Llama a la clase ConexionCashier para brindar una facil y rapida conexion
        ClasesInternas.ConexionCashier.getConexion();
        //Se valida si los datos son autenticos utilizando la clase
        //AutenticacionCashier
        if(aut.Autenticacion(mUser, mPassword) == true){
            CashierMenu cashiermenu = new CashierMenu();
            cashiermenu.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido " + mUser + "!",
                    "Felicidades", JOptionPane.INFORMATION_MESSAGE);
            CashierIdTXT.setText("");
            CashierPassJPF.setText("");
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "USUARIO Y CONTRASEÑA INCORRECTO",
                    "Error de Autenticacion", JOptionPane.ERROR_MESSAGE);
            CashierIdTXT.setText("");
            CashierPassJPF.setText("");
        }
        
    }//GEN-LAST:event_CashierLoginBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CashierIMG;
    private javax.swing.JLabel CashierIdLBL;
    private javax.swing.JTextField CashierIdTXT;
    private javax.swing.JButton CashierLoginBTN;
    private javax.swing.JPasswordField CashierPassJPF;
    private javax.swing.JLabel CashierPassLBL;
    private javax.swing.JLabel PassIMG;
    private javax.swing.JLabel TituloLBL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
