/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Toolkit;

/**
 *
 * @author Vivia Jones
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        setLocationRelativeTo(null);
        initComponents();
        setTitle("Inicio");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainMessage = new javax.swing.JLabel();
        AdminLoginBTN = new javax.swing.JButton();
        CashierLoginBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MainMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMessage.setText("Bienvenidos al Sistema de Facturacion Davis SuperMarket SFW");
        jPanel1.add(MainMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 98));

        AdminLoginBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdminLoginBTN.setText("Admin Login");
        AdminLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(AdminLoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 146, 221, 52));

        CashierLoginBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierLoginBTN.setText("Cashier Login");
        CashierLoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierLoginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CashierLoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 273, 221, 55));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/romero.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 430, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBTNActionPerformed
        // TODO add your handling code here:
        AdminLogin adm = new AdminLogin();
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        dispose();
    }//GEN-LAST:event_AdminLoginBTNActionPerformed

    private void CashierLoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierLoginBTNActionPerformed
        // TODO add your handling code here:
        CashierLogin cash = new CashierLogin();
        cash.setLocationRelativeTo(null);
        cash.setVisible(true);
        dispose();
    }//GEN-LAST:event_CashierLoginBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginBTN;
    private javax.swing.JButton CashierLoginBTN;
    private javax.swing.JLabel MainMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
